apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-app
spec:
  template:
    spec:
      containers:
      - name: hello-world-app  # This must match the name in the original rollout
        image: gcr.io/google-samples/hello-app:1.0  # Change to whatever image you want