apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-app
  # labels:
  #   project: t3apac  # <-- Add your desired project name here
spec:
  template:
    spec:
      containers:
        - name: hello-world-app
          image: quay.io/openshiftdemos/rollouts-demo:red
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      autoPromotionSeconds: 20
      scaleDownDelaySeconds: 300
      activeService: hello-world-active
      previewService: hello-world-preview
      previewReplicaCount: 1
      activeMetadata:
        labels:
          role: active
      previewMetadata:
        labels:
          role: preview
      prePromotionAnalysis:
        templates:
        - templateName: smoke-tests
        args:
        - name: route-host
          value: hello-world-preview-staging.apps.e3c5k7g5w3o7p7w.5vc5.p1.openshiftapps.com

