apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml



resources:
- ../../base
namePrefix: dev-
patchesStrategicMerge:
- replicas.yaml
- strategy.yaml
- patch-route.yaml

commonAnnotations:
  sonarqube-scan: success
  
images:
  - name: quay.io/openshiftdemos/rollouts-demo
    newTag: red