apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
patchesStrategicMerge:
- replicas.yaml
- version.yaml
- strategy.yaml


commonAnnotations:
  sonarqube-scan: success
  
patches:
  - target:
      kind: Route
      name: hello-world-active
    patch: |
      - op: replace
        path: /spec/to/name
        value: dev-hello-world-active