# Active service (production traffic)
apiVersion: v1
kind: Service
metadata:
  name: hello-world-active
spec:
  ports:
  - port: 8080          
    protocol: TCP
    targetPort: 8080     
  selector:
    app: hello-world
    role: active
---
# Preview service (testing traffic)
apiVersion: v1
kind: Service
metadata:
  name: hello-world-preview
spec:
  ports:
  - port: 8081           
    protocol: TCP
    targetPort: 8080     
  selector:
    app: hello-world
    role: preview