apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-world
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/excellaco/argo-manifests.git
        revision: feature/helm
        files:
          - path: env-config/**/config.json
  template:
    metadata:
      name: '{{.env}}-hello-world'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/excellaco/argo-manifests.git
          path: charts/hello-world
          targetRevision: feature/helm
          helm:
            valueFiles:
              - $values/values/common.yaml
              - $values/values/app-version/{{.version}}.yaml
              - $values/values/env-type/{{.type}}.yaml
              - $values/values/regions/{{.region}}.yaml
              - $values/values/envs/{{.env}}.yaml
        - repoURL: https://github.com/excellaco/argo-manifests.git
          targetRevision: feature/helm
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
